//! LargeDict — high-capacity pinyin→hanzi dictionary.
//!
//! Supports two backends:
//! - **TSV** (HashMap): loaded from rime-ice.tsv at runtime (24MB, ~800ms)
//! - **FST** (inputx_fsa::Dict): pre-built binary from `build_dict` tool.
//!   Faster load, memory-efficient, supports frequency scoring + prefix.
//!
//! Both provide exact pinyin lookup O(1) / O(len(pinyin)). FST also
//! supports efficient prefix matching.

use std::collections::HashMap;

fn initials_from_pinyin(raw: &str) -> String {
    inputx_pinyin::segment(raw)
        .first()
        .map(|seg| {
            seg.syllables
                .iter()
                .filter_map(|s| s.chars().next())
                .collect()
        })
        .unwrap_or_default()
}

/// Owned FST data for runtime-loaded dictionaries.
type OwnedFst = inputx_fsa::Dict<Vec<u8>>;

enum Backend {
    /// HashMap-based (loaded from TSV text).
    Map(HashMap<String, Vec<String>>),
    /// FST-based (loaded from pre-built .fst binary via build_dict tool).
    Fst(OwnedFst),
}

impl Default for Backend {
    fn default() -> Self {
        Backend::Map(HashMap::new())
    }
}

impl std::fmt::Debug for Backend {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Backend::Map(m) => write!(f, "Map({} keys)", m.len()),
            Backend::Fst(_) => write!(f, "Fst"),
        }
    }
}

#[derive(Debug, Default)]
pub struct LargeDict {
    backend: Backend,
    /// Initials index: "nh" → ["你好", ...] for jianpin matching.
    initials_index: HashMap<String, Vec<String>>,
}

impl LargeDict {
    pub fn new() -> Self {
        LargeDict::default()
    }

    pub fn len(&self) -> usize {
        match &self.backend {
            Backend::Map(m) => m.len(),
            Backend::Fst(_) => self.initials_index.len(), // approximate
        }
    }

    pub fn is_empty(&self) -> bool {
        match &self.backend {
            Backend::Map(m) => m.is_empty(),
            Backend::Fst(_) => false,
        }
    }

    /// Exact pinyin lookup.
    pub fn exact(&self, pinyin: &str) -> Vec<String> {
        match &self.backend {
            Backend::Map(m) => m.get(pinyin).cloned().unwrap_or_default(),
            Backend::Fst(fst) => fst
                .get(pinyin.as_bytes())
                .into_iter()
                .map(|(item, _freq)| String::from_utf8(item).unwrap_or_default())
                .collect(),
        }
    }

    /// Jianpin (initials-only) lookup — O(1).
    /// "nh" → ["你好", "你还", "年后", ...]
    pub fn jianpin(&self, initials: &str) -> Vec<String> {
        self.initials_index
            .get(initials)
            .cloned()
            .unwrap_or_default()
    }

    /// Load from a file — auto-detects TSV vs FST by extension.
    pub fn load_from_tsv_file(&mut self, path: &str) -> std::io::Result<usize> {
        if path.ends_with(".fst") {
            return self.load_fst_file(path);
        }
        let content = std::fs::read_to_string(path)?;
        let count = self.load_from_tsv_bytes(content.as_bytes());
        Ok(count)
    }

    /// Load a pre-built FST binary (generated by `build_dict` tool).
    /// Also loads cached initials index if available (.idx file next to .fst).
    fn load_fst_file(&mut self, path: &str) -> std::io::Result<usize> {
        let data = std::fs::read(path)?;
        let start = std::time::Instant::now();
        let fst = inputx_fsa::Dict::new(data).map_err(|e| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("invalid FST: {e:?}"),
            )
        })?;

        // Try loading cached jianpin index first.
        let idx_path = format!("{path}.idx");
        if self.try_load_idx_cache(&idx_path, path) {
            eprintln!(
                "[swift-ime] large dict loaded (FST+cache) in {}ms",
                start.elapsed().as_millis()
            );
        } else {
            // Build from scratch and save cache.
            self.build_initials_from_fst(&fst);
            let elapsed = start.elapsed();
            self.save_idx_cache(&idx_path);
            eprintln!(
                "[swift-ime] large dict loaded (FST, built idx) in {}ms",
                elapsed.as_millis()
            );
        }
        self.backend = Backend::Fst(fst);
        Ok(self.len())
    }

    /// Try loading cached jianpin index. Returns true on success.
    /// Only loads if cache is newer than the FST file.
    fn try_load_idx_cache(&mut self, cache_path: &str, fst_path: &str) -> bool {
        let Ok(cache_meta) = std::fs::metadata(cache_path) else {
            return false;
        };
        let Ok(fst_meta) = std::fs::metadata(fst_path) else {
            return false;
        };
        if let (Ok(cache_mtime), Ok(fst_mtime)) = (cache_meta.modified(), fst_meta.modified()) {
            if cache_mtime <= fst_mtime {
                return false;
            } // stale cache
        }
        let Ok(data) = std::fs::read(cache_path) else {
            return false;
        };
        // Format: binary, pairs of (key_len:u8, key_bytes, count:u16, word_len:u8, word_bytes)...
        let mut pos = 0;
        let mut count_keys = 0;
        while pos < data.len() {
            if pos + 1 > data.len() {
                break;
            }
            let key_len = data[pos] as usize;
            pos += 1;
            if pos + key_len > data.len() {
                break;
            }
            let key = String::from_utf8_lossy(&data[pos..pos + key_len]).to_string();
            pos += key_len;
            if pos + 2 > data.len() {
                break;
            }
            let n = u16::from_le_bytes([data[pos], data[pos + 1]]) as usize;
            pos += 2;
            let mut words = Vec::with_capacity(n);
            for _ in 0..n {
                if pos + 1 > data.len() {
                    break;
                }
                let wl = data[pos] as usize;
                pos += 1;
                if pos + wl > data.len() {
                    break;
                }
                words.push(String::from_utf8_lossy(&data[pos..pos + wl]).to_string());
                pos += wl;
            }
            self.initials_index.insert(key, words);
            count_keys += 1;
        }
        count_keys > 0
    }

    /// Save jianpin index cache to disk.
    fn save_idx_cache(&self, cache_path: &str) {
        let mut buf = Vec::new();
        for (key, words) in &self.initials_index {
            buf.push(key.len() as u8);
            buf.extend_from_slice(key.as_bytes());
            buf.extend_from_slice(&(words.len() as u16).to_le_bytes());
            for w in words {
                buf.push(w.len() as u8);
                buf.extend_from_slice(w.as_bytes());
            }
        }
        let _ = std::fs::write(cache_path, &buf);
    }

    fn build_initials_from_fst(&mut self, fst: &OwnedFst) {
        let mut init_map: HashMap<String, Vec<(String, u32)>> = HashMap::new();
        // Iterate all (code, item, value) triples in the Dict.
        fst.prefix_for_each(b"", |code, item, value| {
            let pinyin = std::str::from_utf8(code).unwrap_or("");
            let word = std::str::from_utf8(item).unwrap_or("");
            if !pinyin.is_empty() && !word.is_empty() {
                let init = initials_from_pinyin(pinyin);
                if init.len() >= 2 {
                    init_map
                        .entry(init)
                        .or_default()
                        .push((word.to_string(), value as u32));
                }
            }
        });
        for (init, mut scored) in init_map {
            scored.sort_by(|a, b| {
                b.1.cmp(&a.1)
                    .then_with(|| a.0.chars().count().cmp(&b.0.chars().count()))
            });
            scored.dedup_by(|a, b| a.0 == b.0);
            self.initials_index
                .insert(init, scored.into_iter().map(|(w, _)| w).take(48).collect());
        }
        eprintln!(
            "[swift-ime] jianpin index: {} initials",
            self.initials_index.len()
        );
    }

    /// Load from TSV bytes (for compile-time embedded dicts). Uses HashMap backend.
    pub fn load_from_tsv_bytes(&mut self, data: &[u8]) -> usize {
        let mut count = 0;
        let start = std::time::Instant::now();

        // Pass 1: collect entries and count word frequencies.
        let mut freq: std::collections::HashMap<String, u32> = std::collections::HashMap::new();
        let mut raw_entries: Vec<(String, String)> = Vec::new();

        if let Ok(s) = std::str::from_utf8(data) {
            for line in s.lines() {
                let line = line.trim();
                if line.is_empty() || line.starts_with('#') {
                    continue;
                }
                if let Some((pinyin, word)) = line.split_once('\t') {
                    if !pinyin.is_empty() && !word.is_empty() {
                        let key = pinyin.replace(' ', "");
                        *freq.entry(word.to_string()).or_default() += 1;
                        raw_entries.push((key, word.to_string()));
                        count += 1;
                    }
                }
            }
        }

        // Pass 2: build HashMap with frequency-aware entries.
        let mut entries: HashMap<String, Vec<String>> = HashMap::new();
        for (key, word) in raw_entries {
            entries.entry(key).or_default().push(word);
        }
        for vals in entries.values_mut() {
            vals.sort_by(|a, b| {
                let len_cmp = a.chars().count().cmp(&b.chars().count());
                if len_cmp != std::cmp::Ordering::Equal {
                    return len_cmp;
                }
                let fa = freq.get(a).copied().unwrap_or(0);
                let fb = freq.get(b).copied().unwrap_or(0);
                fb.cmp(&fa)
            });
            vals.dedup();
        }
        // Build initials index.
        let mut initials_map: HashMap<String, Vec<(String, u32)>> = HashMap::new();
        for (pinyin, words) in &entries {
            let init = initials_from_pinyin(pinyin);
            if init.len() >= 2 {
                for w in words {
                    let f = *freq.get(w).unwrap_or(&1);
                    initials_map
                        .entry(init.clone())
                        .or_default()
                        .push((w.clone(), f));
                }
            }
        }
        for (init, mut scored) in initials_map {
            scored.sort_by(|a, b| {
                let len_cmp = a.0.chars().count().cmp(&b.0.chars().count());
                if len_cmp != std::cmp::Ordering::Equal {
                    return len_cmp;
                }
                b.1.cmp(&a.1)
            });
            scored.dedup_by(|a, b| a.0 == b.0);
            self.initials_index
                .insert(init, scored.into_iter().map(|(w, _)| w).take(48).collect());
        }
        let elapsed = start.elapsed();
        let keys = entries.len();
        eprintln!(
            "[swift-ime] large dict loaded (TSV): {count} entries, {keys} keys in {}ms",
            elapsed.as_millis()
        );
        self.backend = Backend::Map(entries);
        count
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exact_lookup() {
        let mut dict = LargeDict::new();
        let data = "xiayige\t\u{4e0b}\u{4e00}\u{4e2a}\nzheshi\t\u{8fd9}\u{662f}\n";
        dict.load_from_tsv_bytes(data.as_bytes());
        assert_eq!(dict.exact("xiayige"), vec!["\u{4e0b}\u{4e00}\u{4e2a}"]); // 下一个
        assert_eq!(dict.exact("zheshi"), vec!["\u{8fd9}\u{662f}"]); // 这是
        assert!(dict.exact("unknown").is_empty());
    }

    #[test]
    fn empty_lookup() {
        let dict = LargeDict::new();
        assert!(dict.exact("anything").is_empty());
    }
}
